version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    # ホスト側のポート：コンテナのポート
    ports:
      - '3333:3000'
    # ホスト側のsrcをコンテナのappにマウント
    volumes:
      - ./src:/app/src
    # 起動時のカレントフォルダ
    working_dir: /app